- name: create directory for facts
  file:
    path: /etc/ansible/facts.d/
    state: directory

- name: copy afacts.fact template
  template: src=afacts.fact dest=/etc/ansible/facts.d/ force={{afacts_rewrite}}

- name: regather facts
  setup:
  when: afacts_regather
